### ISSUE TITLE
2-MTSLIA not very receptive to patterns

### ISSUE THREAD

**Issue by antecedent** [alenaks/SigmaPie#6]
Can't help but notice this throughout my experimentation.

In cases like the following, shouldn't the inferred grammar be a bit more similar to the one used for generating the sample? I'm not so sure what happens here. Do the (otherwise innocuous) restrictions in the source grammar conspire to create overlapping tiers?

```python
import sigmapie

A = list('tuvwxyz')

gen = sigmapie.MTSL(k=2, polar='n')
gen.alphabet = A
gen.grammar = {
    ('x', 'y', 'w'):       [('w', 'y')], 
    ('z', 'v', 'w'):       [('v', 'w')], 
    ('w', 'u', 'v', 't'):  [('v', 't')], 
    ('x', 'y', 'v', 't'):  [('t', 'x')], 
    ('u', 'y', 't'):       [('t', 't')]
}

infer = sigmapie.MTSL(k=2, polar='n')
infer.alphabet = A
infer.data = gen.generate_sample(1000)

print(len(set(infer.data)))

infer.learn()

print(infer.grammar)
```

Output:
```
658
{('t', 'u', 'v', 'w', 'x', 'y', 'z'): [('w', 'y'), ('v', 't'), ('v', 'w'), ('t', 't'), ('t', 'x')]}
```

**Comment by antecedent** [comment]
Please consider merging the pull request; it was just some ordinary gimmicks of implementation that had been preventing the algorithm from converging with that dataset.

**Comment by alenaks** [comment]
Absolutely beautiful, thank you very much! I merged your PR.
